##########################################################
#                  Join Maxscale cluster                 #
##########################################################

- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.1.0'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: MAXSCALE - Create maxscale database user
  community.mysql.mysql_user:
    login_user: '{{ DBADMINUSER }}'
    login_password: '{{ DBADMINPASSWD }}'
    name: '{{ MAXSCALE_USER }}'
    password: '{{ MAXSCALE_USER_PASSWORD }}'
    host_all: true
    state: present
    priv:
      'mysql.user': 'SELECT'
      'mysql.db': 'SELECT'
      'mysql.tables_priv': 'SELECT'
      'mysql.columns_priv': 'SELECT'
      'mysql.procs_priv': 'SELECT'
      'mysql.proxies_priv': 'SELECT'
      'mysql.roles_mapping': 'SELECT'
      '*.*': 'SHOW DATABASES'
  no_log: True

- name: MAXSCALE - Create maxscale monitor database user
  community.mysql.mysql_user:
    login_user: '{{ DBADMINUSER }}'
    login_password: '{{ DBADMINPASSWD }}'
    name: '{{ MAXSCALE_MONITOR_USER }}'
    password: '{{ MAXSCALE_MONITOR_USER_PASSWORD }}'
    host_all: true
    state: present
    priv:
      '*.*': 'REPLICATION CLIENT, SUPER, RELOAD'
  no_log: True

- name: MAXSCALE_CLUSTER - Get current list of servers in MariaDB-Monitor section
  ansible.builtin.set_fact:
    MARIADB_MONITOR_SERVERS: "{{ lookup('ansible.builtin.ini', 'servers', section='MariaDB-Monitor', file='/etc/maxscale.cnf.d/medulla_master.cnf') | split }}"
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ MAXSCALE_FQDN }}'

- name: MAXSCALE_CLUSTER - Append server to list of servers in MariaDB-Monitor section
  ansible.builtin.set_fact:
    MARIADB_MONITOR_SERVERS: "{{ MARIADB_MONITOR_SERVERS | combine([SERVER_FQDN.split(".")[0]]) }}"

- name: MAXSCALE_CLUSTER - Get current list of servers in Read-Only-Service section
  ansible.builtin.set_fact:
    READONLY_SERVICE_SERVERS: "{{ lookup('ansible.builtin.ini', 'servers', section='Read-Only-Service', file='/etc/maxscale.cnf.d/medulla_master.cnf') | split }}"
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ MAXSCALE_FQDN }}'

- name: MAXSCALE_CLUSTER - Append server to list of servers in Read-Only-Service section
  ansible.builtin.set_fact:
    READONLY_SERVICE_SERVERS: "{{ READONLY_SERVICE_SERVERS | combine([SERVER_FQDN.split(".")[0]]) }}"

- name: MAXSCALE_CLUSTER - Configure mariadb server in maxscale
  community.general.ini_file:
    path: /etc/maxscale.cnf.d/medulla_master.cnf
    section: '{{ item.section }}'
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { section: '{{ SERVER_FQDN.split(".")[0] }}', parameter: 'type', value: 'server' }
    - { section: '{{ SERVER_FQDN.split(".")[0] }}', parameter: 'address', value: '{{ SERVER_FQDN }}' }
    - { section: '{{ SERVER_FQDN.split(".")[0] }}', parameter: 'port', value: '{{ MARIADB_SERVER_PORT }}' }
    - { section: '{{ SERVER_FQDN.split(".")[0] }}', parameter: 'protocol', value: 'MariaDBBackend' }
    - { section: 'MariaDB-Monitor', parameter: 'servers', value: '{{ MARIADB_MONITOR_SERVERS | join(,) }}' }
    - { section: 'Read-Only-Service', parameter: 'servers', value: '{{ READONLY_SERVICE_SERVERS | join(,) }}' }
  notify:
    - MAXSCALE_CLUSTER - Restart maxscale
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ MAXSCALE_FQDN }}'

- name: MAXSCALE_CLUSTER - Restart maxscale with the new parameters
  ansible.builtin.meta: flush_handlers
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ MAXSCALE_FQDN }}'
