---
- name: Pulse4Update
  hosts: all
  remote_user: root
  serial: 1

  pre_tasks:
    - name: Log start
      lineinfile: 
        path: /tmp/pulse4update.log
        create: yes
        mode: 0644
        line: "{{ lookup('pipe', 'date +%H:%M') }} {{ ansible_hostname }}: Start"
      delegate_to: localhost

  roles:
    - pulse4update

  tasks:
    - name: Log start
      lineinfile:
        path: /tmp/pulse4update.log
        line: {{ item }}
      loop:
        - "{{ lookup('pipe', 'date +%H:%M') }} {{ ansible_hostname }}: End"
        - ""
      delegate_to: localhost
...
