##########################################################
#   Enable synch to CDN and configure relay to use CDN   #
##########################################################

- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.1.0'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: ENABLE_CDN - Configure package_watching.ini.local
  community.general.ini_file:
    path: /etc/pulse-xmpp-agent/package_watching.ini.local
    section: rsynctocdn
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'enable', value: 'True' }
    - { parameter: 'ssh_remoteuser', value: '{{ SSH_REMOTEUSER }}' }
    - { parameter: 'ssh_servername', value: '{{ SSH_REMOTESERVER }}' }
    - { parameter: 'ssh_destpath', value: '{{ SSH_REMOTE_PATH }}' }
  notify:
    - ENABLE_CDN - Restart pulse-package-watching
  when:
    - PULSEMAIN_FQDN == ''

- name: ENABLE_CDN - Configure package_watching.ini.local
  community.general.ini_file:
    path: /etc/pulse-xmpp-agent/package_watching.ini.local
    section: rsynctocdn
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'enable', value: 'True' }
    - { parameter: 'ssh_remoteuser', value: '{{ SSH_REMOTEUSER }}' }
    - { parameter: 'ssh_servername', value: '{{ SSH_REMOTESERVER }}' }
    - { parameter: 'ssh_destpath', value: '{{ SSH_REMOTE_PATH }}' }
  notify:
    - ENABLE_CDN - Restart pulse-package-watching
  delegate_to: '{{ PULSEMAIN_FQDN }}'
  when:
    - PULSEMAIN_FQDN is defined
    - PULSEMAIN_FQDN != ''

- name: ENABLE_CDN - Configure pkgs.ini.local
  community.general.ini_file:
    path: /etc/mmc/plugins/pkgs.ini.local
    section: integrity_checks
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'generate_hash', value: 'True' }
    - { parameter: 'keyAES32', value: '{{ AES_KEY }}' }
  notify:
    - ENABLE_CDN - Restart mmc-agent
  when:
    - PULSEMAIN_FQDN == ''

- name: ENABLE_CDN - Configure pkgs.ini.local
  community.general.ini_file:
    path: /etc/mmc/plugins/pkgs.ini.local
    section: integrity_checks
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'generate_hash', value: 'True' }
    - { parameter: 'keyAES32', value: '{{ AES_KEY }}' }
  notify:
    - ENABLE_CDN - Restart mmc-agent
  delegate_to: '{{ PULSEMAIN_FQDN }}'
  when:
    - PULSEMAIN_FQDN is defined
    - PULSEMAIN_FQDN != ''

- name: ENABLE_CDN - Configure loaddeployment.ini.local
  community.general.ini_file:
    path: /etc/pulse-xmpp-agent-substitute/loaddeployment.ini.local
    section: parameters
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'send_hash', value: 'True' }
    - { parameter: 'keyAES32', value: '{{ AES_KEY }}' }
  notify:
    - ENABLE_CDN - Restart pulse-xmpp-master-substitute-deployment
  when:
    - PULSEMAIN_FQDN == ''

- name: ENABLE_CDN - Configure loaddeployment.ini.local
  community.general.ini_file:
    path: /etc/pulse-xmpp-agent-substitute/loaddeployment.ini.local
    section: parameters
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'send_hash', value: 'True' }
    - { parameter: 'keyAES32', value: '{{ AES_KEY }}' }
  notify:
    - ENABLE_CDN - Restart pulse-xmpp-master-substitute-deployment
  delegate_to: '{{ PULSEMAIN_FQDN }}'
  when:
    - PULSEMAIN_FQDN is defined
    - PULSEMAIN_FQDN != ''

- name: ENABLE_CDN - Configure Relay server applicationdeploymentjson.ini.local
  community.general.ini_file:
    path: /etc/pulse-xmpp-agent/applicationdeploymentjson.ini.local
    section: parameters
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'cdn_enable', value: 'True' }
    - { parameter: 'cdn_baseurl', value: '{{ CDN_BASEURL }}' }
    - { parameter: 'cdn_token', value: '{{ CDN_TOKEN }}' }
  notify:
    - ENABLE_CDN - Restart pulse-xmpp-agent-relay

- name: ENABLE_CDN - Force restart of services after configuration
  ansible.builtin.meta: flush_handlers

- name: ENABLE_CDN - Ensure package_watching is running
  ansible.builtin.systemd:
    name: pulse-package-watching
    state: started
    enabled: yes
    masked: no

- name: ENABLE_CDN - Make sure ssh key exists on pulsemain
  ansible.builtin.user:
    name: '{{ SSH_USER }}'
    generate_ssh_key: yes
    ssh_key_bits: 2048
  register: pulsemain_sshkey
  when:
    - PULSEMAIN_FQDN == ''

- name: ENABLE_CDN - !!!!! IMPORTANT MESSAGE !!!!!
  ansible.builtin.debug:
    msg: 
    - Please make sure the following key is added to {{ SSH_REMOTEUSER }} account on {{ SSH_REMOTESERVER }}
    - '{{ pulsemain_sshkey.ssh_public_key }}'
  when:
    - PULSEMAIN_FQDN == ''

- name: ENABLE_CDN - Make sure ssh key exists on pulsemain
  ansible.builtin.user:
    name: '{{ SSH_USER }}'
    generate_ssh_key: yes
    ssh_key_bits: 2048
  register: pulsemain_sshkey
  delegate_to: '{{ PULSEMAIN_FQDN }}'
  when:
    - PULSEMAIN_FQDN is defined
    - PULSEMAIN_FQDN != ''

- name: ENABLE_CDN - !!!!! IMPORTANT MESSAGE !!!!!
  ansible.builtin.debug:
    msg: 
    - Please make sure the following key is added to {{ SSH_REMOTEUSER }} account on {{ SSH_REMOTESERVER }}
    - '{{ pulsemain_sshkey.ssh_public_key }}'
  when:
    - PULSEMAIN_FQDN != ''
