##########################################################
#                   SSH server setup                     #
##########################################################

- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.1.0'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: SSH - Make sure /etc/ssh/sshd_config.d exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: SSH - Setup alternate SSH port if defined
  ansible.builtin.template:
    src: pulse.conf.j2
    dest: '/etc/ssh/sshd_config.d/pulse.conf'
    mode: '0644'
    owner: root
    group: root
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - SSH - Restart ssh
  when:
    - REVERSE_SSH_PORT != ''
