##########################################################
#                   Join LDAP cluster                    #
##########################################################

- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.0.0'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: LDAP_CLUSTER - Add the OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  ignore_errors: true

- name: LDAP_CLUSTER - Get contents of cn=config.ldif file from main server
  ansible.builtin.slurp:
    src: '{{ SLAPD_D_PATH }}/cn=config.ldif'
  register: configldif
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ PULSEMAIN_IP }}'

- name: LDAP_CLUSTER - Create a list of all olcServerID records from main server
  ansible.builtin.set_fact:
    CLUSTER_SERVERS_LIST: "{{ configldif['content'] | b64decode | regex_findall('olcServerID: ([0-9]+ .+)', multiline=True, ignorecase=True) }}"

- name: LDAP_CLUSTER - Get contents of local cn=config.ldif file
  ansible.builtin.slurp:
    src: '{{ SLAPD_D_PATH }}/cn=config.ldif'
  register: configldif

- name: LDAP_CLUSTER - Get local olcServerID
  ansible.builtin.set_fact:
    LOCAL_CLUSTER_SERVER: "{{ configldif['content'] | b64decode | regex_findall('olcServerID: ([0-9]+ .+)', multiline=True, ignorecase=True) }}"

- name: LDAP_CLUSTER - Define admin password
  ansible.builtin.command: slappasswd -s {{ LDAPADMINPASSWD }}
  register: command_result

- name: LDAP_CLUSTER - Set LDAPADMINPASSWD_ENCR for syncthing
  ansible.builtin.set_fact:
    LDAPADMINPASSWD_ENCR: "{{ command_result.stdout }}"

- name: LDAP_CLUSTER - Append local olcServerID to CLUSTER_SERVERS_LIST
  ansible.builtin.set_fact:
    CLUSTER_SERVERS_LIST: "{{ CLUSTER_SERVERS_LIST + LOCAL_CLUSTER_SERVER }}"

- name: LDAP_CLUSTER - Copy synch_modify.ldif to /tmp on main server
  ansible.builtin.template:
    src: synch_modify.ldif.j2
    dest: /tmp/synch_modify.ldif
    mode: '0644'
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ PULSEMAIN_IP }}'

- name: LDAP_CLUSTER - Enable replication of cn=config database on main server
  ansible.builtin.command: 'ldapmodify -c -Q -Y EXTERNAL -H ldapi:/// -f /tmp/synch_modify.ldif'
  register: command_result
  failed_when:
    - (command_result.rc != 0) and (command_result.rc != 20)
  vars:
    ansible_ssh_user: root
  delegate_to: '{{ PULSEMAIN_IP }}'

- name: LDAP_CLUSTER - Copy synch_modify.ldif to /tmp
  ansible.builtin.template:
    src: synch_modify.ldif.j2
    dest: /tmp/synch_modify.ldif
    mode: '0644'

- name: LDAP_CLUSTER - Enable replication of cn=config database
  ansible.builtin.command: 'ldapmodify -c -Q -Y EXTERNAL -H ldapi:/// -f /tmp/synch_modify.ldif'
  register: command_result
  failed_when:
    - (command_result.rc != 0) and (command_result.rc != 20)
