- name: PULSE - Restart apache
  ansible.builtin.systemd:
    name: '{{ APACHE_DAEMON }}'
    state: restarted
    daemon_reload: yes

- name: PULSE - Restart samba
  ansible.builtin.systemd:
    name: '{{ SAMBA_DAEMON }}'
    state: restarted
    daemon_reload: yes

- name: PULSE - Reload apache on main server
  ansible.builtin.systemd:
    name: '{{ APACHE_DAEMON }}'
    state: reloaded
  delegate_to: '{{ PULSEMAIN_FQDN }}'
