---

##########################################################
#                         Version                        #
##########################################################

 - name: VERSION - Set version for this playbook
   set_fact:
     PLAYBOOK_VERSION: '3.3.0'

 - name: VERSION - Display version
   debug:
     msg:
     - "Pulse4Rollback Playbook Version: {{ PLAYBOOK_VERSION }}"
         
##########################################################
#                         Checks                         #
##########################################################

 - name: PRE-CHECKS - Check platform requierement
   fail:
     msg: The OS platform is outdated ( {{ ansible_distribution }} , {{ ansible_distribution_version }} )
   when: 
     - ansible_distribution == 'CentOS'
     - ansible_distribution_version < 7.6
