##########################################################
#                     Maxscale setup                     #
##########################################################

- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.1.0'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: MAXSCALE - Add the OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: MAXSCALE - Install tools needed for the setup
  ansible.builtin.yum:
    state: latest
    pkg:
      - crudini
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: MAXSCALE - Install tools needed for the setup
  ansible.builtin.apt:
    state: latest
    pkg:
      - crudini
  when:
    - ansible_distribution == 'Debian'

- name: MAXSCALE - Install maxscale
  ansible.builtin.yum:
    pkg:
      - maxscale
      - mariadb
    state: latest
  when:
    - ansible_distribution == 'CentOS'

- name: MAXSCALE - Install maxscale
  ansible.builtin.yum:
    pkg:
      - maxscale
      - mariadb
    state: latest
  when:
    - ansible_distribution == 'RedHat'

- name: MAXSCALE - Install maxscale
  ansible.builtin.apt:
    pkg:
      - maxscale
      - mariadb-client
    state: latest
  when:
    - ansible_distribution == 'Debian'

- name: MAXSCALE - Enable bin logs for replication
  community.general.ini_file:
    path: '{{ MARIADB_CONF_PATH }}/{{ SERVER_CONF_FILE }}'
    section: mysqld
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { option: 'server-id', value: '1' }
    - { option: 'log_bin', value: '/var/log/mysql/mysql-bin.log' }
    - { option: 'expire_logs_days', value: '10' }
    - { option: 'max_binlog_size', value: '100M' }
  delegate_to: '{{ MASTER_FQDN }}'
  notify:
    - MAXSCALE - Restart mariadb on master

- name: MAXSCALE - Create maxscale database user
  community.mysql.mysql_user:
    login_user: '{{ DBADMINUSER }}'
    login_password: '{{ DBADMINPASSWD }}'
    login_port: '{{ MASTER_PORT }}'
    name: '{{ MAXSCALE_USER }}'
    password: '{{ MAXSCALE_USER_PASSWORD }}'
    host: '%'
    state: present
    priv:
      'mysql.user': 'SELECT'
      'mysql.db': 'SELECT'
      'mysql.tables_priv': 'SELECT'
      'mysql.columns_priv': 'SELECT'
      'mysql.procs_priv': 'SELECT'
      'mysql.proxies_priv': 'SELECT'
      'mysql.roles_mapping': 'SELECT'
      '*.*': 'SHOW DATABASES'
  delegate_to: '{{ MASTER_FQDN }}'
  no_log: True

- name: MAXSCALE - Create maxscale monitor database user
  community.mysql.mysql_user:
    login_user: '{{ DBADMINUSER }}'
    login_password: '{{ DBADMINPASSWD }}'
    login_port: '{{ MASTER_PORT }}'
    name: '{{ MAXSCALE_MONITOR_USER }}'
    password: '{{ MAXSCALE_MONITOR_USER_PASSWORD }}'
    host: '%'
    state: present
    priv:
      '*.*': 'REPLICATION CLIENT, REPLICA MONITOR, FILE, CONNECTION ADMIN, SUPER, RELOAD, PROCESS, SHOW DATABASES, EVENT, READ_ONLY ADMIN, REPLICATION SLAVE'
      'mysql.user': 'SELECT'
      'mysql.global_priv': 'SELECT'
  delegate_to: '{{ MASTER_FQDN }}'
  no_log: True

- name: MAXSCALE - Remove sections that will be present in medulla_master.cnf
  community.general.ini_file:
    path: /etc/maxscale.cnf
    section: '{{ item }}'
    state: absent
    backup: yes
  with_items:
    - MariaDB-Monitor
    - Read-Write-Service
    - Read-Only-Service
    - server1
  notify:
    - MAXSCALE - Restart maxscale

- name: MAXSCALE - Add Splitter-Listener to maxscale.cnf
  community.general.ini_file:
    path: /etc/maxscale.cnf
    section: Splitter-Listener
    option: '{{ item.parameter }}'
    value: '{{ item.value }}'
    backup: yes
  with_items:
    - { parameter: 'type', value: 'listener' }
    - { parameter: 'service', value: 'Splitter-Service' }
    - { parameter: 'protocol', value: 'MariaDBClient' }
    - { parameter: 'port', value: '{{ MAXSCALE_SPLITTER_PORT }}' }
  notify:
    - MAXSCALE - Restart maxscale

- name: MAXSCALE - Configure Admin GUI
  community.general.ini_file:
    path: /etc/maxscale.cnf
    section: maxscale
    option: admin_secure_gui
    value: 'false'
    backup: yes
  notify:
    - MAXSCALE - Restart maxscale

- name: MAXSCALE - Configure maxscale
  ansible.builtin.template:
    src: medulla_master.cnf.j2
    dest: /etc/maxscale.cnf.d/medulla_master.cnf
    mode: '0644'
    backup: yes
  notify:
    - MAXSCALE - Restart maxscale

- name: MAXSCALE - Allow proxied requests on master mariadb from maxscale
  community.general.ini_file:
    path: '{{ MARIADB_CONF_PATH }}/{{ SERVER_CONF_FILE }}'
    section: mariadb
    option: proxy-protocol-networks
    value: "::1, localhost, {{ IP_ADDRESS }}/{{ NETMASK | ansible.utils.ipaddr('prefix') }}"
    backup: yes
  delegate_to: '{{ MASTER_FQDN }}'
  notify:
    - MAXSCALE - Restart mariadb on master

- name: MAXSCALE - Restart maxscale with the new parameters
  ansible.builtin.meta: flush_handlers

- name: MAXSCALE - Ensure maxscale is running
  ansible.builtin.systemd:
    name: maxscale
    state: started
    enabled: yes
    masked: no

