STDISCOSRV_URL: '' # STDISCOSRV_URL can be forced otherwise will be obtained from main server if STMAIN_HOST is defined
STRELAYSRV_URL: '' # STRELAYSRV_URL can be forced otherwise will be obtained from main server if STMAIN_HOST is defined
STAPIKEY: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
STROOTPASSWD: '{{ ROOT_PASSWORD }}'
STROOTPASSWD_HASHED: "{{ STROOTPASSWD | password_hash('bcrypt') }}"
DEVICE_NAME: '{{ ansible_hostname }}'
STMAIN_HOST: '{{ PULSEMAIN_IP }}' # STMAIN_HOST must be set on relays and cluster members
