- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.1.0'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: SYNCTHING - Stop service for deleting any previous configuration
  ansible.builtin.systemd:
    name: syncthing@{{ item }}
    state: stopped
  with_items:
    - syncthing
    - syncthing-depl
  ignore_errors: true

- name: SYNCTHING - Stop medulla relay service for deleting any previous configuration
  ansible.builtin.systemd:
    name: pulse-xmpp-agent-relay
    state: stopped
  ignore_errors: true

- name: SYNCTHING - Reset syncthing
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/var/lib/syncthing/.config'
    - '/var/lib/syncthing/Sync'
    - '/var/lib/syncthing-depl/.config'
    - '/var/lib/syncthing-depl/Sync'

- name: SYNCTHING - Delete configuration initialisation marker
  ansible.builtin.file:
    path: /var/lib/syncthing/.dbinitialised
    state: absent
