- name: Medulla Main
  gather_facts: true
  hosts: mmcmain
  remote_user: root
  serial: 1

  pre_tasks:
    - name: MEDULLAMAIN - Set version for this playbook
      ansible.builtin.set_fact:
        PLAYBOOK_VERSION: '5.0.0'

    - name: MEDULLAMAIN - Display version
      ansible.builtin.debug:
        msg:
        - "Playbook Version: {{ PLAYBOOK_VERSION }}"

  roles:
    - base
    - security
    - pki
    - local_certs
    - apache
    - php
    - ldap
    - mariadb
    - ejabberd
    - { role: syncthing_discosrv, when: (ansible_domain != 'siveo.net') }
    - { role: syncthing_relay, when: (ansible_domain != 'siveo.net') }
    - syncthing
    - { role: urbackup, when: (not URBACKUP_DISABLED) }
    - ssh
    - { role: glpi, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'glpi') }
    - { role: itsm-ng, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'itsm-ng') }
    - tomcat
    - guacamole
    - grafana
    - nfs
    - mmc
    - { role: substitute_agent, SUBS_LONG_TYPE: 'subscription' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'assessor' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'inventory' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'registration' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'logger' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'deployment' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'monitoring' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'reconfigurator' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'updates' }
    - { role: syncthing_share_folder, SHARE_NAME: 'baseremoteagent', SHARE_PATH: '/var/lib/pulse2/xmpp_baseremoteagent/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'downloads', SHARE_PATH: '/var/lib/pulse2/clients/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'global', SHARE_PATH: '/var/lib/pulse2/packages/sharing/global/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'winupdates', SHARE_PATH: '/var/lib/pulse2/packages/sharing/winupdates/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - medulla_osupdates
    - relay_agent
    - samba
    - pulse_file_browser
    - { role: pulse_packageserver, when: (not IMAGING_DISABLED) }
    - { role: pxe_registration, when: (not IMAGING_DISABLED) }
    - { role: syncthing_share_folder, SHARE_NAME: 'postinst', SHARE_PATH: '/var/lib/pulse2/imaging/postinst/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly', when: (not IMAGING_DISABLED) }
    - { role: pulse_imaging, when: (not IMAGING_DISABLED) }
    - pulse_main
