- name: Cleanup
  gather_facts: true
  hosts: all
  remote_user: root
  serial: 1
  # environment: "{{ proxy_env }}"

  pre_tasks:
    - name: CLEANUP - Set version for this playbook
      ansible.builtin.set_fact:
        PLAYBOOK_VERSION: '5.0.0'

    - name: CLEANUP - Display version
      ansible.builtin.debug:
        msg:
        - "Playbook Version: {{ PLAYBOOK_VERSION }}"

  roles:
    - ldap_cleanup
    - ejabberd_cleanup
    - syncthing_cleanup
    - { role: glpi_cleanup, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'glpi') }
    - { role: itsm-ng_cleanup, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'itsm-ng') }
    - grafana_cleanup
    - mmc_cleanup
    - mariadb_cleanup
