- name: Medulla Main Cluster
  gather_facts: true
  hosts: mmccluster
  remote_user: root
  serial: 1
  # environment: "{{ proxy_env }}"

  pre_tasks:
    - name: MEDULLAMAIN_CLUSTER - Set version for this playbook
      ansible.builtin.set_fact:
        PLAYBOOK_VERSION: '5.0.0'

    - name: MEDULLAMAIN_CLUSTER - Display version
      ansible.builtin.debug:
        msg:
        - "Playbook Version: {{ PLAYBOOK_VERSION }}"

  roles:
    - base
    - security
    - local_certs
    - apache
    - php
    - ldap
    - ldap_join_cluster
    - mariadb
    - ejabberd
    - ejabberd_join_cluster
    - syncthing
    - { role: urbackup, when: (not URBACKUP_DISABLED) }
    - ssh
    - tomcat
    - guacamole
    - grafana
    - nfs
    - mmc
    - { role: substitute_agent, SUBS_LONG_TYPE: 'subscription', SUBS_NAME: 'subscription{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'assessor', SUBS_NAME: 'assessor{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'inventory', SUBS_NAME: 'inventory{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'registration', SUBS_NAME: 'registration{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'logger', SUBS_NAME: 'logger{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'deployment', SUBS_NAME: 'deployment{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'monitoring', SUBS_NAME: 'monitoring{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'updates', SUBS_NAME: 'updates{{ SUBS_INDEX }}', DISABLE_INITIAL_SERVICE: true }
    - { role: syncthing_share_folder, SHARE_NAME: 'baseremoteagent', SHARE_PATH: '/var/lib/pulse2/xmpp_baseremoteagent/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'downloads', SHARE_PATH: '/var/lib/pulse2/clients/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'global', SHARE_PATH: '/var/lib/pulse2/packages/sharing/global/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'winupdates', SHARE_PATH: '/var/lib/pulse2/packages/sharing/winupdates/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - relay_agent
    - samba
    - pulse_file_browser
    - { role: pulse_packageserver, when: (not IMAGING_DISABLED) }
    - { role: pxe_registration, when: (not IMAGING_DISABLED) }
    - { role: syncthing_share_folder, SHARE_NAME: 'postinst', SHARE_PATH: '/var/lib/pulse2/imaging/postinst/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly', when: (not IMAGING_DISABLED) }
    - { role: pulse_imaging, when: (not IMAGING_DISABLED) }
    - pulse_main
