- name: Pulse Relay
  gather_facts: true
  hosts: ars
  remote_user: root

  pre_tasks:
    - name: PULSERELAY - Set version for this playbook
      ansible.builtin.set_fact:
        PLAYBOOK_VERSION: '5.0.0'

    - name: PULSERELAY - Display version
      ansible.builtin.debug:
        msg:
        - "Playbook Version: {{ PLAYBOOK_VERSION }}"

  roles:
    - base
    - security
    - mariadb
    - ejabberd
    - syncthing
    - ssh
    - guacamole
    - nfs
    - relay_agent
    - pulse_packageserver
    - pulse_imaging
    - pulse_relay
