- name: Medulla Relay - Part 1
  gather_facts: true
  hosts: ars
  remote_user: root

  pre_tasks:
    - name: MEDULLARELAY - Set version for this playbook
      ansible.builtin.set_fact:
        PLAYBOOK_VERSION: '5.0.0'

    - name: MEDULLARELAY - Display version
      ansible.builtin.debug:
        msg:
        - "Playbook Version: {{ PLAYBOOK_VERSION }}"

  roles:
    - base
    - security
    - local_certs
    - mariadb
    - ejabberd
    - apache
    - syncthing
    - ssh
    - tomcat
    - guacamole
    - nfs
    - { role: pulse_packageserver, when: (not IMAGING_DISABLED) }
    - { role: pxe_registration, when: (not IMAGING_DISABLED) }
    - samba

- name: Medulla Relay - Part 2
  gather_facts: true
  hosts: ars
  serial: 1
  remote_user: root
  roles:
    - { role: syncthing_share_folder, SHARE_NAME: 'postinst', SHARE_PATH: '/var/lib/pulse2/imaging/postinst/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly', when: (not IMAGING_DISABLED) }
    - { role: syncthing_share_folder, SHARE_NAME: 'baseremoteagent', SHARE_PATH: '/var/lib/pulse2/xmpp_baseremoteagent/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'downloads', SHARE_PATH: '/var/lib/pulse2/clients/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'global', SHARE_PATH: '/var/lib/pulse2/packages/sharing/global/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - { role: syncthing_share_folder, SHARE_NAME: 'winupdates', SHARE_PATH: '/var/lib/pulse2/packages/sharing/winupdates/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }
    - relay_agent

- name: Medulla Relay - Part 3
  gather_facts: true
  hosts: mmcmain
  remote_user: root
  roles:
    - { role: syncthing_share_folder, SHARE_NAME: '{{ PKGS_SHARE_NAME }}', SHARE_PATH: '/var/lib/pulse2/packages/sharing/{{ PKGS_SHARE_NAME }}/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }

- name: Medulla Relay - Part 4
  gather_facts: true
  hosts: ars
  remote_user: root
  roles:
    - { role: syncthing_share_folder, SHARE_NAME: '{{ PKGS_SHARE_NAME }}', SHARE_PATH: '/var/lib/pulse2/packages/sharing/{{ PKGS_SHARE_NAME }}/', MAIN_SHARE_TYPE: 'sendreceive', RELAY_SHARE_TYPE: 'receiveonly' }

- name: Medulla Relay - Part 5
  gather_facts: true
  hosts: ars
  remote_user: root
  roles:
    - pulse_relay
    - { role: pulse_imaging, when: (not IMAGING_DISABLED) }
