- name: SIVEO environments - MMC
  gather_facts: true
  remote_user: root
  hosts: mmcmain
  roles:
    - security
    - siveodev
    - siveotest

- name: SIVEO environments - ARS
  gather_facts: true
  remote_user: root
  hosts: ars
  roles:
    - security
    - siveodev
