- name: SIVEO environments - MMC
  gather_facts: true
  remote_user: root
  hosts: mmcmain
  environment: "{{ proxy_env }}"
  roles:
    - security
    - siveodev

- name: SIVEO environments - ARS
  gather_facts: true
  remote_user: root
  hosts: ars
  environment: "{{ proxy_env }}"
  roles:
    - security
    - siveodev
