- name: Medulla Package Server feature
  gather_facts: true
  hosts: all
  remote_user: root
  environment: "{{ proxy_env }}"
  roles:
    - apache
    - syncthing
    - local_certs
    - pulse_packageserver
