- name: Medulla OS Updates feature
  gather_facts: true
  hosts: mmc
  remote_user: root
  # environment: "{{ proxy_env }}"
  roles:
    - apache
    - php
    - { role: 'mariadb', when: DBHOST == 'localhost' }
    - ldap
    - { role: glpi, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'glpi') }
    - { role: itsm-ng, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'itsm-ng') }
    - local_certs
    - ejabberd
    - grafana
    - mmc
    - syncthing
    - { role: substitute_agent, SUBS_LONG_TYPE: 'updates' }
    - { role: syncthing_share_folder, SHARE_NAME: 'winupdates', SHARE_PATH: '/var/lib/pulse2/packages/sharing/winupdates/', MAIN_SHARE_TYPE: 'sendonly', RELAY_SHARE_TYPE: 'sendreceive' }
    - { role: syncthing_share_folder, SHARE_NAME: 'winupdatesmajor', SHARE_PATH: '/var/lib/pulse2/packages/sharing/winupdatesmajor/', MAIN_SHARE_TYPE: 'sendonly', RELAY_SHARE_TYPE: 'sendreceive' }
    - medulla_osupdates
