---

##########################################################
#                         Version                        #
##########################################################

 - name: VERSION - Set version for this playbook
   set_fact:
     PLAYBOOK_VERSION: '3.3.0'

 - name: VERSION - Display version
   debug:
     msg:
     - "Pulse4Update Playbook Version: {{ PLAYBOOK_VERSION }}"
     
     
##########################################################
#                         Checks                         #
##########################################################

 - name: PRE-CHECKS - Check platform requierement
   fail:
     msg: The OS platform is outdated ( {{ ansible_distribution }} , {{ ansible_distribution_version }} )
   when: 
     - ansible_distribution == 'CentOS'
     - ansible_distribution_version < 7.6
   

##########################################################
#                     Upgrade Pulse                      #
##########################################################

 - name: UPGRADE - Upgrade packages from pulse repo
   yum:
     update_cache: yes
     disablerepo: '*'
     enablerepo: pulse
     name: '*'
     state: latest
   when:
     - ansible_distribution == 'CentOS'
   no_log: True


##########################################################
#                     Final steps                        #
##########################################################

 - name: FINAL - Restart pulse services
   systemd:
     name: '{{ item }}'
     state: restarted
     daemon_reload: yes
   with_items: 
     - pulse-xmpp-agent-relay
     - pulse-package-watching
   when:
     - INSTALL_TYPE != 'p'
   no_log: True

 - name: FINAL - Check if ssh, syncthing and ejabberd are properly setup
   wait_for:
     port: '{{ item }}'
     delay: 5
     timeout: 30
   with_items:
     - 2222
     - 22000
     - 5222
   register: check_ports
   ignore_errors: True
   no_log: True

 - name: FINAL - Stop syncthing if errors
   systemd:
     name: syncthing@syncthing
     enabled: no
     state: stopped
   when:
     - check_ports.failed is defined
   no_log: True

 - name: FINAL - Print error and exit
   fail:
     msg: The checks failed. Please restart the job.
   when:
     - check_ports.failed is defined
